name: Generate ASCII Artwork with Shell Script
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: list Repo Files
          run: ls -ltra

        - name: Executing Shell Script
          run: ./ascii-script.sh
