name: Exploring Variables and Secrets
on:
  # push
  schedule:
    - cron: "*/1 * * * *"

env:
    CONTAINER_REGISTRY: docker.io
    IMAGE_NAME: github-actions-nginx

jobs:
    # docker:
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Docker Build
    #     run: docker build -t docker.io/dockerUsername/imageName:latest

    #   - name: Docker Login
    #     run: docker login --username=dockerUsername --password=s3cUrePaSsw0rd

    #   - name: Docker Publish
    #     run: docker push docker.io/dockerUsername/imageName:latest

    # deploy:
    #   needs: docker
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: Docker Run
    #     run: docker run -d -p 8080:80 docker.io/dockerusername/imageName:latest

### Environment Variables at STEP/JOB/Workflow level ###
    docker:
      runs-on: ubuntu-latest
      steps:
      - name: Docker Build
        run: echo docker build -t $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

      - name: Docker Login
        run: echo docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Publish
        run: echo docker push $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest

    deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
      - name: Docker Run
        run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/${{ vars.DOCKER_USERNAME }}/$IMAGE_NAME:latest